import keyMirror from 'key-mirror';

export default keyMirror({
	GET_ENTERPRISE_SEARCH_SUCCESS: null,//获取公司信息  
    GET_ENTERPRISE_SEARCH_FALURE: null,
    GET_ENTERPRISE_NUMBER_SUCCESS: null,//获取查询的公司数量
    GET_ENTERPRISE_NUMBER_FAILURE: null,
    GET_ENTERPRISE_LITERATURE_SUCCESS: null,//查询公司科技文献
    GET_ENTERPRISE_LITERATURE_FAILURE: null,
    GET_ENTERPRISE_LITERATURENUMBER_SUCCESS: null,//查询公司科技文献条数
	GET_ENTERPRISE_LITERATURENUMBER_FAILURE: null,
    GET_ENTERPRISE_NEWS_SUCCESS: null,//查询公司新闻
    GET_ENTERPRISE_NEWS_FAILURE: null,
    GET_ENTERPRISE_NEWSNUMBER_SUCCESS: null,//查询新闻条数
	GET_ENTERPRISE_NEWSNUMBER_FAILURE: null,
    GET_ENTERPRISE_PATENT_SUCCESS: null,//查询公司专利
    GET_ENTERPRISE_PATENT_FAILURE: null,
    GET_ENTERPRISE_PATENTNUMBER_SUCCESS: null,//查询公司专利条数
	GET_ENTERPRISE_PATENTNUMBER_FAILURE: null,
    GET_ENTERPRISE_RECRUIT_SUCCESS: null,//查询公司招聘
    GET_ENTERPRISE_RECRUIT_FAILURE: null,
    GET_ENTERPRISE_RECRUITNUMBER_SUCCESS: null,//查询公司招聘条数
	GET_ENTERPRISE_RECRUITNUMBER_FAILURE: null,
    GET_ENTERPRISE_COPYRIGHT_SUCCESS: null,//查询公司著作权
	GET_ENTERPRISE_COPYRIGHT_FAILURE: null,
    GET_RELATIONSHIP_SUCCESS: null,//获取公司投资图
    GET_RELATIONSHIP_FAILURE: null,
});